version: 2

sources:
  - name: main
    tables:
      - name: raw_users
      - name: raw_events
      - name: raw_inventory_items
      - name: raw_order_items
      - name: raw_orders
      - name: raw_products